// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://czrncrtlifxaurlemwsu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN6cm5jcnRsaWZ4YXVybGVtd3N1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIxNjIxOTIsImV4cCI6MjA1NzczODE5Mn0.sBrgW6CRXMZfu7Nnionk2x36TA24ZGUtIhkfjikolSM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);